### ISSUE TITLE
key in preview mode is needed

### ISSUE THREAD

**Issue by maartenkling** [collective/collective.embedly#19]
preview is broken, it should have the key in url or you will get 403

**Comment by maartenkling** [comment]
http://api.embed.ly/1/oembed?format=json&url=youtube.com/watch%3Fv%3Du6xnKIhdixs

HTTP Status: 403
Upstream message:You must pass your api key as the 'key' parameter. Get an api key at http://embed.ly/signup

You are receiving this message because, well, something went wrong. The above message should be super descriptive and ultra helpful (At least we hope it is). If you feel you got this message in error or have additional questions please see our documentation or email support@embed.ly

DocumentationSupportEmbedly

**Comment by frisi** [comment]
@maartenkling could you test the branch and let us know if it fixes your problems? thanks, harald
